spring:
  main:
    allow-circular-references: true
  profiles:
    active: dev
#mybatis 分页插件
pagehelper:
  helperDialect: mysql


server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
